[package]
name = "ritk-jpeg"
version = "0.2.0"
authors.workspace = true
repository.workspace = true
publish = true
edition = "2021"
license.workspace = true
description = "JPEG grayscale image I/O for RITK"

[dependencies]
ritk-image = { path = "../ritk-image", version = "0.4.0" }
ritk-spatial = { path = "../ritk-spatial", version = "0.2.0" }
anyhow = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }
coeus-core = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
