DQ = chr(34)
W = []
def w(*p): W.append("".join(str(x) for x in p))
w("//! DICOM series writer using dicom-rs v0.8.2.")
w("//! Transfer syntax: Explicit VR LE. Each .dcm has 128-byte preamble + DICM magic.")
w()
w("use anyhow::{bail, Context, Result};")
w("use burn::tensor::backend::Backend;")
w("use dicom::core::smallvec::SmallVec;")
w("use dicom::core::{DataElement, PrimitiveValue, Tag, VR};")
w("use dicom::object::meta::FileMetaTableBuilder;")
w("use dicom::object::InMemDicomObject;")
w("use ritk_core::image::Image;")
w("use std::marker::PhantomData;")
w("use std::path::{Path, PathBuf};")
w()
w("fn generate_series_uid() -> String {")
w("    let t = std::time::SystemTime::now()")
w("        .duration_since(std::time::UNIX_EPOCH)")
w("        .unwrap_or_default()")
w("        .as_nanos();")
w("    format!(", DQ, "2.25.{}", DQ, ", t)")
w("}")
w()
w("fn generate_instance_uid(series_uid: &str, instance: usize) -> String {")
w("    format!(", DQ, "{}.{}", DQ, ", series_uid, instance + 1)")
w("}")
w()
w("pub fn write_dicom_series<B: Backend, P: AsRef<Path>>(path: P, image: &Image<B, 3>) -> Result<()> {")
w("    let path = path.as_ref();")
w("    let [depth, rows, cols] = image.shape();")
w("    if depth == 0 || rows == 0 || cols == 0 {")
w("        bail!(", DQ, "DICOM: depth={depth} rows={rows} cols={cols} must be >0", DQ, ");")
w("    }")
w("    let series_dir = ensure_series_directory(path)?;")
w("    let series_uid = generate_series_uid();")
w("    let study_uid = series_uid.clone();")
w("    let series_instance_uid = format!(", DQ, "{}.1", DQ, ", series_uid);")
w("    let td = image.data().clone().into_data();")
w("    let all_data: &[f32] = td")
w("        .as_slice::<f32>()")
w("        .context(", DQ, "image tensor must contain f32 data", DQ, ")?;")
w("    let slice_len = rows * cols;")
w("    for z in 0..depth {")
w("        let slice_offset = z * slice_len;")
w("        let slice_f32 = &all_data[slice_offset..slice_offset + slice_len];")
w("        let (min_val, max_val) = slice_f32.iter().copied()")
w("            .fold((f32::INFINITY, f32::NEG_INFINITY), |(mn, mx), v| (mn.min(v), mx.max(v)));")
w("        let (rescale_slope, rescale_intercept) = if (max_val - min_val).abs() <= f32::EPSILON {")
w("            (1.0_f32, min_val)")
w("        } else {")
w("            ((max_val - min_val) / 65535.0_f32, min_val)")
w("        };")
w("        let pixel_u16: Vec<u16> = slice_f32.iter()")
w("            .map(|&v| ((v - rescale_intercept) / rescale_slope).round() as u16)")
w("            .collect();")
w("        let sop_instance_uid = generate_instance_uid(&series_uid, z);")
w("        let mut obj = InMemDicomObject::new_empty();")
w("        obj.put(DataElement::new(Tag(0x0008,0x0016),VR::UI,PrimitiveValue::from(", DQ, "1.2.840.10008.5.1.4.1.1.7", DQ, ")));")
w("        obj.put(DataElement::new(Tag(0x0008,0x0018),VR::UI,PrimitiveValue::from(sop_instance_uid.as_str())));")
w("        obj.put(DataElement::new(Tag(0x0008,0x0060),VR::CS,PrimitiveValue::from(", DQ, "OT", DQ, ")));")
w("        obj.put(DataElement::new(Tag(0x0020,0x000D),VR::UI,PrimitiveValue::from(study_uid.as_str())));")
w("        obj.put(DataElement::new(Tag(0x0020,0x000E),VR::UI,PrimitiveValue::from(series_instance_uid.as_str())));")
w("        obj.put(DataElement::new(Tag(0x0020,0x0013),VR::IS,PrimitiveValue::from(format!(", DQ, "{}", DQ, ", z+1))));")
w("        obj.put(DataElement::new(Tag(0x0028,0x0010),VR::US,PrimitiveValue::from(rows as u16)));")
w("        obj.put(DataElement::new(Tag(0x0028,0x0011),VR::US,PrimitiveValue::from(cols as u16)));")
w("        obj.put(DataElement::new(Tag(0x0028,0x0100),VR::US,PrimitiveValue::from(16_u16)));")
w("        obj.put(DataElement::new(Tag(0x0028,0x0101),VR::US,PrimitiveValue::from(16_u16)));")
w("        obj.put(DataElement::new(Tag(0x0028,0x0102),VR::US,PrimitiveValue::from(15_u16)));")
w("        obj.put(DataElement::new(Tag(0x0028,0x0103),VR::US,PrimitiveValue::from(0_u16)));")
w("        obj.put(DataElement::new(Tag(0x0028,0x1053),VR::DS,PrimitiveValue::from(format!(", DQ, "{:.6}", DQ, ",rescale_slope))));")
w("        obj.put(DataElement::new(Tag(0x0028,0x1052),VR::DS,PrimitiveValue::from(format!(", DQ, "{:.6}", DQ, ",rescale_intercept))));")
w("        obj.put(DataElement::new(Tag(0x0028,0x0004),VR::CS,PrimitiveValue::from(", DQ, "MONOCHROME2", DQ, ")));")
w("        obj.put(DataElement::new(Tag(0x7FE0,0x0010),VR::OW,PrimitiveValue::U16(SmallVec::from_vec(pixel_u16))));")
w("        let file_obj = obj.with_meta(")
w("            FileMetaTableBuilder::new()")
w("                .media_storage_sop_class_uid(", DQ, "1.2.840.10008.5.1.4.1.1.7", DQ, ")")
w("                .media_storage_sop_instance_uid(sop_instance_uid.as_str())")
w("                .transfer_syntax(", DQ, "1.2.840.10008.1.2.1", DQ, "),)")
w("            .map_err(|e| anyhow::anyhow!(", DQ, "DICOM meta failed slice {z}: {e}", DQ, "))?;")
w("        let slice_path = series_dir.join(format!(", DQ, "slice_{z:04}.dcm", DQ, "));")
w("        file_obj.write_to_file(&slice_path)")
w("            .map_err(|e| anyhow::anyhow!(", DQ, "write slice {z} failed: {e}", DQ, "))?;")
w("    }")
w("    Ok(())")
w("}")
w()
w("pub struct DicomWriter<B> { _phantom: PhantomData<B> }")
w("impl<B> DicomWriter<B> {")
w("    pub fn new() -> Self { Self { _phantom: PhantomData } }")
w("    pub fn series_path<P: AsRef<Path>>(path: P) -> PathBuf { path.as_ref().to_path_buf() }")
w("}")
w("impl<B> Default for DicomWriter<B> { fn default() -> Self { Self::new() } }")
w()
w("fn ensure_series_directory(path: &Path) -> Result<PathBuf> {")
w("    if path.exists() {")
w("        if !path.is_dir() { bail!(", DQ, "DICOM output path is not a directory", DQ, "); }")
w("        return Ok(path.to_path_buf());")
w("    }")
w("    std::fs::create_dir_all(path)")
w("        .with_context(|| ", DQ, "failed to create DICOM series output directory", DQ, ")?;")
w("    Ok(path.to_path_buf())")
w("}")
w()
w("#[cfg(test)]")
w("mod tests {")
w("    use super::*;")
w("    use burn::tensor::{Shape, Tensor, TensorData};")
w("    use ritk_core::image::Image;")
w("    use ritk_core::spatial::{Direction, Point, Spacing};")
w("    type Backend = burn_ndarray::NdArray<f32>;")
w()
w("    fn make_image(depth: usize, rows: usize, cols: usize, fill: f32) -> Image<Backend, 3> {")
w("        let device = Default::default();")
w("        let data = vec![fill; depth * rows * cols];")
w("        let tensor = Tensor::<Backend, 3>::from_data(")
w("            TensorData::new(data, Shape::new([depth, rows, cols])), &device,")
w("        );")
w("        Image::new(tensor, Point::new([0.0,0.0,0.0]),")
w("            Spacing::new([1.0,1.0,1.0]), Direction::identity())")
w("    }")
w()
w("    #[test]")
w("    fn test_writer_rejects_zero_dimension() {")
w("        let image = make_image(0, 4, 4, 0.5);")
w("        let temp = tempfile::tempdir().unwrap();")
w("        let path = temp.path().join(", DQ, "series", DQ, ");")
w("        let result = write_dicom_series(&path, &image);")
w("        assert!(result.is_err(), ", DQ, "zero depth must be rejected", DQ, ");")
w("    }")
w()
w("    #[test]")
w("    fn test_writer_creates_correct_number_of_slice_files() {")
w("        let image = make_image(3, 4, 5, 0.5);")
w("        let temp = tempfile::tempdir().unwrap();")
w("        let path = temp.path().join(", DQ, "series", DQ, ");")
w("        write_dicom_series(&path, &image).expect(", DQ, "write must succeed", DQ, ");")
w("        assert!(path.is_dir());")
w("        let count = std::fs::read_dir(&path).unwrap()")
w("            .filter_map(|e| e.ok())")
w("            .filter(|e| e.path().extension().and_then(|s| s.to_str()) == Some(", DQ, "dcm", DQ, "))")
w("            .count();")
w("        assert_eq!(count, 3, ", DQ, "must produce exactly 3 .dcm files", DQ, ");")
w("    }")
w()
w("    #[test]")
w("    fn test_writer_slice_files_are_nonempty() {")
w("        let image = make_image(2, 8, 8, 100.0);")
w("        let temp = tempfile::tempdir().unwrap();")
w("        let path = temp.path().join(", DQ, "series", DQ, ");")
w("        write_dicom_series(&path, &image).expect(", DQ, "write must succeed", DQ, ");")
w("        for entry in std::fs::read_dir(&path).unwrap().filter_map(|e| e.ok()) {")
w("            if entry.path().extension().and_then(|s| s.to_str()) == Some(", DQ, "dcm", DQ, ") {")
w("                let size = std::fs::metadata(entry.path()).unwrap().len();")
w("                assert!(size > 200, ", DQ, "DICOM slice must be >200 bytes, got {}", DQ, ", size);")
w("            }")
w("        }")
w("    }")
w()
w("    #[test]")
w("    fn test_writer_dcm_starts_with_dicom_magic() {")
w("        let image = make_image(1, 4, 4, 0.0);")
w("        let temp = tempfile::tempdir().unwrap();")
w("        let path = temp.path().join(", DQ, "series", DQ, ");")
w("        write_dicom_series(&path, &image).expect(", DQ, "write must succeed", DQ, ");")
w("        let dcm_path = path.join(", DQ, "slice_0000.dcm", DQ, ");")
w("        let bytes = std::fs::read(&dcm_path).expect(", DQ, "slice file must exist", DQ, ");")
w("        assert!(bytes.len() >= 132, ", DQ, "DICOM file must be >=132 bytes", DQ, ");")
w("        assert_eq!(&bytes[128..132], b", DQ, "DICM", DQ, ",")
w("            ", DQ, "DICOM magic bytes must be present at offset 128", DQ, ");")
w("    }")
w("}")
with open("crates/ritk-io/src/format/dicom/writer.rs", "w") as fh:
    fh.write("\n".join(W) + "\n")
print("writer.rs written:", len(W), "lines")
