//! Speckle (multiplicative) noise filter.

use super::fastnorm::hash;
use super::mersenne::MersenneTwister;
use super::DEFAULT_NOISE_SEED;
use anyhow::Result;
use ritk_core::image::Image;
use ritk_image::tensor::Backend;
use ritk_tensor_ops::{extract_vec, rebuild};

/// Speckle (multiplicative) noise filter.
///
/// Applies multiplicative Gamma-distributed noise (mean 1, variance `σ²`):
///
/// ```text
/// I'(x) = I(x) · Γ(x),   E[Γ] = 1,  Var[Γ] = σ²
/// ```
///
/// Matches `sitk.SpeckleNoise` (run single-threaded): the Gamma variate is
/// generated by Marsaglia–Tsang acceptance–rejection over ITK's MT19937 uniform
/// stream (`GetVariateWithOpenUpperRange`), reproducing ITK bit-for-bit.
///
/// # Complexity
/// O(N) where N is the number of voxels.
pub struct SpeckleNoiseFilter {
    /// Standard deviation of the multiplicative noise factor (default: 0.05).
    pub std: f64,
    /// Random seed (matched against SimpleITK's `uint32` seed; default: 42).
    pub seed: u32,
}

impl SpeckleNoiseFilter {
    /// Create a filter with the given multiplicative noise std.
    pub fn new(std: f64) -> Self {
        Self {
            std,
            seed: DEFAULT_NOISE_SEED as u32,
        }
    }

    /// Set the random seed (builder pattern).
    pub fn with_seed(mut self, seed: u32) -> Self {
        self.seed = seed;
        self
    }

    /// Apply speckle noise to a 3-D image, matching `sitk.SpeckleNoise`
    /// single-threaded.
    pub fn apply<B: Backend>(&self, image: &Image<B, 3>) -> Result<Image<B, 3>> {
        let (vals, dims) = extract_vec(image)?;
        // Degenerate variance ⇒ Gamma collapses to 1 (identity).
        if self.std == 0.0 {
            return Ok(rebuild(vals, dims, image));
        }
        let mut gen = MersenneTwister::new(hash(self.seed, 0));

        // Gamma(k, theta) with mean k*theta = 1, variance k*theta^2 = std^2.
        let theta = self.std * self.std;
        let k = 1.0 / theta;
        let floork = k.floor();
        let delta = k - floork;
        let v0 = std::f64::consts::E / (std::f64::consts::E + delta);

        let out: Vec<f32> = vals
            .iter()
            .map(|&v| {
                // Marsaglia–Tsang gamma for the fractional shape `delta`.
                let (mut xi, mut nu);
                loop {
                    let v1 = 1.0 - gen.variate_open_upper();
                    let v2 = 1.0 - gen.variate_open_upper();
                    let v3 = 1.0 - gen.variate_open_upper();
                    if v1 <= v0 {
                        xi = v2.powf(1.0 / delta);
                        nu = v3 * xi.powf(delta - 1.0);
                    } else {
                        xi = 1.0 - v2.ln();
                        nu = v3 * (-xi).exp();
                    }
                    if nu <= (-xi).exp() * xi.powf(delta - 1.0) {
                        break;
                    }
                }
                let mut gamma = xi;
                for _ in 0..(floork as i64) {
                    gamma -= (1.0 - gen.variate_open_upper()).ln();
                }
                gamma *= theta;
                (gamma * v as f64) as f32
            })
            .collect();
        Ok(rebuild(out, dims, image))
    }
}

impl Default for SpeckleNoiseFilter {
    fn default() -> Self {
        Self::new(0.05)
    }
}
