[package]
name = "ritk-python"
version = "0.12.79"
description = "Python extension bindings for RITK"
authors.workspace = true
repository.workspace = true
publish = false
edition = "2021"
license.workspace = true

[lib]
name = "_ritk"
crate-type = ["cdylib", "rlib"]

[features]
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = { workspace = true }
numpy = { workspace = true }
coeus-core = { workspace = true }
coeus-tensor = { workspace = true }
ritk-core = { path = "../ritk-core", version = "0.10.0" }
ritk-image = { path = "../ritk-image", version = "0.4.0" }
ritk-spatial = { path = "../ritk-spatial", version = "0.2.0" }
ritk-statistics = { path = "../ritk-statistics", version = "0.4.0" }
ritk-interpolation = { path = "../ritk-interpolation", version = "0.5.0" }
ritk-transform = { path = "../ritk-transform", version = "0.2.0" }
ritk-filter = { path = "../ritk-filter", version = "0.3.0" }
ritk-segmentation = { path = "../ritk-segmentation", version = "0.3.0" }
ritk-io = { path = "../ritk-io", version = "0.3.0" }
ritk-registration = { path = "../ritk-registration", version = "0.54.0" }
anyhow = { workspace = true }
