[package]
name = "ritk-mif"
version = "0.2.1"
authors.workspace = true
repository.workspace = true
publish = true
edition = "2021"
license.workspace = true
description = "MRtrix .mif image format I/O for RITK"
keywords.workspace = true
categories.workspace = true
homepage.workspace = true

[dependencies]
ritk-image = { path = "../ritk-image", version = "0.3.0" }
ritk-spatial = { path = "../ritk-spatial", version = "0.2.0" }
ritk-diffusion-scheme = { path = "../ritk-diffusion-scheme", version = "0.2.0" }
coeus-core = { workspace = true }
anyhow = { workspace = true }
bytemuck = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
