[package]
name = "ritk-core"
version = "0.10.0"
description = "Core medical image processing algorithms for RITK"
authors.workspace = true
repository.workspace = true
publish = true
edition = "2021"
license.workspace = true

[features]
default = []

[dependencies]
ritk-spatial = { path = "../ritk-spatial", version = "0.2.0" }
ritk-image = { path = "../ritk-image", version = "0.3.0" }
ritk-morphology = { path = "../ritk-morphology", version = "0.2.0" }
ritk-annotation = { path = "../ritk-annotation", version = "0.2.0" }
ritk-tensor-ops = { path = "../ritk-tensor-ops", version = "0.2.0" }
ritk-statistics = { path = "../ritk-statistics", version = "0.4.0" }
coeus-core = { workspace = true }
coeus-tensor = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
coeus-core = { workspace = true }
coeus-tensor = { workspace = true }
