//! Comparison benchmark: jagged `HashSet` adjacency vs CSR-shaped
//! [`Adjacency`] for Laplacian surface smoothing.
//!
//! The "before" side is the pre-conversion `build_adjacency` (a
//! `Vec<HashSet<u32>>` collapsed to `Vec<Vec<u32>>`, per-vertex heap
//! allocation, `HashSet`-defined neighbor order) and its `laplacian_step`.
//! Both are re-implemented here because the conversion deletes them from
//! `smooth.rs`; this bench is the retained comparison instrument.
//!
//! The "after" side is the public [`Adjacency`] build and a traversal over
//! its contiguous sorted neighbor runs.
//!
//! # Measured performance (release build, x86-64)
//!
//! To be re-recorded on the merge of the CSR conversion; the figures in the
//! 2026-08-06 backlog entry are unrecoverable (the original bench file was
//! lost before merge) and are regenerated by this instrument.
//!
//! # Regression sentinel
//!
//! The CSR build must beat the jagged build on interior grids — the flat
//! neighbor buffer avoids a per-vertex allocation and the traversal slices
//! contiguous runs. A regression below the jagged path is a layout defect.
use std::collections::HashSet;

use criterion::{criterion_group, criterion_main, BenchmarkId, Criterion};
use ritk_vtk::domain::filters::smooth::Adjacency;
use ritk_vtk::domain::vtk_data_object::VtkPolyData;

/// Quad grid mesh: `(cells + 1)²` vertices, `cells²` quad polygons.
fn quad_grid(cells: usize) -> VtkPolyData {
    let rows = cells + 1;
    let mut points = Vec::with_capacity(rows * rows);
    for r in 0..rows {
        for c in 0..rows {
            points.push([c as f32, r as f32, 0.0]);
        }
    }
    let mut polygons = Vec::with_capacity(cells * cells);
    for r in 0..cells {
        for c in 0..cells {
            let tl = r * rows + c;
            polygons.push(vec![
                tl as u32,
                (tl + 1) as u32,
                (tl + rows + 1) as u32,
                (tl + rows) as u32,
            ]);
        }
    }
    VtkPolyData {
        points,
        polygons,
        ..Default::default()
    }
}

/// Pre-conversion jagged build: `Vec<HashSet<u32>>` collapsed to
/// `Vec<Vec<u32>>`.
fn build_adjacency_jagged(poly: &VtkPolyData) -> Vec<Vec<u32>> {
    let n = poly.points.len();
    let mut adj: Vec<HashSet<u32>> = vec![HashSet::new(); n];
    for polygon in &poly.polygons {
        let k = polygon.len();
        for i in 0..k {
            let a = polygon[i];
            let b = polygon[(i + 1) % k];
            adj[a as usize].insert(b);
            adj[b as usize].insert(a);
        }
    }
    for line in &poly.lines {
        for i in 0..line.len().saturating_sub(1) {
            adj[line[i] as usize].insert(line[i + 1]);
            adj[line[i + 1] as usize].insert(line[i]);
        }
    }
    adj.into_iter().map(|s| s.into_iter().collect()).collect()
}

/// One Laplacian step over the jagged adjacency.
fn laplacian_step_jagged(pts: &[[f32; 3]], adj: &[Vec<u32>], lambda: f32) -> Vec<[f32; 3]> {
    pts.iter()
        .enumerate()
        .map(|(i, &p)| {
            let neighbors = &adj[i];
            if neighbors.is_empty() {
                p
            } else {
                let k = neighbors.len() as f32;
                let sum = neighbors.iter().fold([0.0_f32; 3], |acc, &j| {
                    let q = pts[j as usize];
                    [acc[0] + q[0], acc[1] + q[1], acc[2] + q[2]]
                });
                let mean = [sum[0] / k, sum[1] / k, sum[2] / k];
                [
                    p[0] * (1.0 - lambda) + mean[0] * lambda,
                    p[1] * (1.0 - lambda) + mean[1] * lambda,
                    p[2] * (1.0 - lambda) + mean[2] * lambda,
                ]
            }
        })
        .collect()
}

/// One Laplacian step over the CSR adjacency.
fn laplacian_step_csr(pts: &[[f32; 3]], adj: &Adjacency, lambda: f32) -> Vec<[f32; 3]> {
    pts.iter()
        .enumerate()
        .map(|(i, &p)| {
            let neighbors = adj.neighbors_of(i);
            if neighbors.is_empty() {
                p
            } else {
                let k = neighbors.len() as f32;
                let sum = neighbors.iter().fold([0.0_f32; 3], |acc, &j| {
                    let q = pts[j as usize];
                    [acc[0] + q[0], acc[1] + q[1], acc[2] + q[2]]
                });
                let mean = [sum[0] / k, sum[1] / k, sum[2] / k];
                [
                    p[0] * (1.0 - lambda) + mean[0] * lambda,
                    p[1] * (1.0 - lambda) + mean[1] * lambda,
                    p[2] * (1.0 - lambda) + mean[2] * lambda,
                ]
            }
        })
        .collect()
}

fn bench_adjacency_build(c: &mut Criterion) {
    let mut group = c.benchmark_group("smooth_adjacency_build");

    for &cells in &[64_usize, 128, 256] {
        let mesh = quad_grid(cells);
        let jagged = build_adjacency_jagged(&mesh);
        let csr = Adjacency::build(&mesh);
        assert_eq!(
            jagged.len(),
            mesh.points.len(),
            "both builds must produce one run per vertex"
        );

        group.bench_with_input(
            BenchmarkId::new("jagged", cells),
            &mesh,
            |b, mesh| {
                b.iter(|| std::hint::black_box(build_adjacency_jagged(mesh)));
            },
        );
        group.bench_with_input(
            BenchmarkId::new("csr", cells),
            &mesh,
            |b, mesh| {
                b.iter(|| std::hint::black_box(Adjacency::build(mesh)));
            },
        );

        // Parity spot-check: CSR run must be a sorted permutation of the
        // jagged run (jagged order is HashSet-defined, so compare as sets).
        for v in 0..mesh.points.len() {
            let mut jag = jagged[v].clone();
            jag.sort_unstable();
            assert_eq!(csr.neighbors_of(v), &jag[..], "vertex {v} parity");
        }
    }

    group.finish();
}

fn bench_laplacian_step(c: &mut Criterion) {
    let mut group = c.benchmark_group("smooth_laplacian_step");

    for &cells in &[64_usize, 128, 256] {
        let mesh = quad_grid(cells);
        let jagged = build_adjacency_jagged(&mesh);
        let csr = Adjacency::build(&mesh);
        let pts = mesh.points.clone();

        group.bench_with_input(
            BenchmarkId::new("jagged", cells),
            &(pts.as_slice(), jagged.as_slice()),
            |b, &(pts, jagged)| {
                b.iter(|| {
                    std::hint::black_box(laplacian_step_jagged(pts, jagged, 0.5));
                });
            },
        );
        group.bench_with_input(
            BenchmarkId::new("csr", cells),
            &(pts.as_slice(), &csr),
            |b, &(pts, csr)| {
                b.iter(|| {
                    std::hint::black_box(laplacian_step_csr(pts, csr, 0.5));
                });
            },
        );
    }

    group.finish();
}

criterion_group!(benches, bench_adjacency_build, bench_laplacian_step);
criterion_main!(benches);
