"""Type stubs for the ``_ritk.connectome`` submodule (PyO3/maturin).

All signatures derived from ``ritk-python/src/connectome/``.

Array conventions: label volumes are ``[Z, Y, X]``, and ``spacing``, ``origin``,
and ``direction`` are given outermost-axis first — the same order an ``Image``
reports. Streamlines are ``[N, 3]`` float arrays in the parcellation's physical
frame.
"""

from __future__ import annotations

from typing import Any, Sequence

class Parcellation:
    def __init__(
        self,
        labels: Any,
        spacing: Sequence[float],
        origin: Sequence[float],
        direction: Sequence[float] | None = None,
        region_names: list[tuple[int, str]] | None = None,
    ) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    @property
    def region_count(self) -> int: ...
    @property
    def region_labels(self) -> list[int]: ...
    @property
    def shape(self) -> list[int]: ...
    def labels(self) -> Any: ...
    def name_of(self, label: int) -> str | None: ...
    def label_at(self, point: Sequence[float]) -> int | None: ...
    def region_statistics(self) -> list[dict[str, Any]]: ...

class GraphMeasures:
    def __repr__(self) -> str: ...
    @property
    def node_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def density(self) -> float: ...
    @property
    def characteristic_path_length(self) -> float | None: ...
    @property
    def reachable_pair_fraction(self) -> float: ...
    @property
    def global_efficiency(self) -> float: ...
    @property
    def component_sizes(self) -> list[int]: ...
    @property
    def modularity(self) -> float: ...
    @property
    def community_count(self) -> int: ...
    def degree(self) -> Any: ...
    def strength(self) -> Any: ...
    def clustering(self) -> Any: ...
    def weighted_clustering(self) -> Any: ...
    def betweenness(self) -> Any: ...
    def local_efficiency(self) -> Any: ...
    def communities(self) -> Any: ...

class ConnectivityMatrix:
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    @property
    def region_labels(self) -> list[int]: ...
    @property
    def accounting(self) -> dict[str, int]: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def density(self) -> float: ...
    def weights(self) -> Any: ...
    def measures(self) -> GraphMeasures: ...
    def rich_club(
        self,
        ensemble_size: int,
        seed: int,
        swaps_per_edge: int | None = None,
    ) -> tuple[list[dict[str, Any]], float]: ...

def build_connectivity_matrix(
    parcellation: Parcellation,
    streamlines: Sequence[Any],
    assignment_radius: float | None = None,
    weighting: str | None = None,
) -> ConnectivityMatrix: ...
